
import { Stock } from './types';

export const PORTFOLIO: Stock[] = [
  { name: 'ENAGÁS', ticker: 'BME:ENG', shares: 350 },
  { name: 'INDITEX', ticker: 'BME:ITX', shares: 100 },
  { name: 'REDEIA', ticker: 'BME:RED', shares: 350 },
  { name: 'TÉCNICAS REUNIDAS', ticker: 'BME:TRE', shares: 100 },
  { name: 'MFE MEDIA EUROPA', ticker: 'BME:MFEA', shares: 140 },
  { name: 'VISCOFAN', ticker: 'BME:VIS', shares: 30 },
  { name: 'NATIONAL GRID', ticker: 'LON:NG', shares: 290 },
  { name: 'BATS', ticker: 'LON:BATS', shares: 100 },
  { name: 'VODAFONE', ticker: 'LON:VOD', shares: 1000 },
  { name: 'ADMIRAL GROUP', ticker: 'LON:ADM', shares: 50 },
  { name: 'LEGAL & GENERAL', ticker: 'LON:LGEN', shares: 500 },
  { name: 'IMPERIAL BRANDS', ticker: 'LON:IMB', shares: 100 },
  { name: 'GLAXOSMITHKLINE', ticker: 'LON:GSK', shares: 100 },
  { name: 'RECKITT BENCKISER', ticker: 'LON:RKT', shares: 33 },
  { name: 'DIAGEO', ticker: 'LON:DGE', shares: 100 },
  { name: 'SHELL', ticker: 'LON:SHEL', shares: 100 },
  { name: 'BASF', ticker: 'ETR:BAS', shares: 25 },
  { name: 'BAYER', ticker: 'ETR:BAYN', shares: 50 },
  { name: 'BMW', ticker: 'ETR:BMW', shares: 25 },
  { name: 'MERCEDES BENZ GROUP', ticker: 'ETR:MBG', shares: 30 },
  { name: 'SIEMENS', ticker: 'ETR:SIE', shares: 15 },
  { name: 'PFIZER', ticker: 'NYSE:PFE', shares: 75 },
  { name: 'PEPSICO', ticker: 'NASDAQ:PEP', shares: 20 },
  { name: 'GENERAL MILLS', ticker: 'NYSE:GIS', shares: 25 },
  { name: 'LYONDELLBASELL', ticker: 'NYSE:LYB', shares: 25 },
  { name: 'UNILEVER', ticker: 'AMS:UNA', shares: 44 },
  { name: 'URW', ticker: 'EPA:URW', shares: 30 },
  { name: 'AENA', ticker: 'BME:AENA', shares: 200 },
  { name: 'IBERDROLA', ticker: 'BME:IBE', shares: 205 },
  { name: 'EBRO', ticker: 'BME:EBRO', shares: 50 },
  { name: 'LOGISTA', ticker: 'BME:LOG', shares: 75 },
  { name: 'SANTANDER', ticker: 'BME:SAN', shares: 300 },
  { name: '3M', ticker: 'NYSE:MMM', shares: 20 },
  { name: 'EXXON', ticker: 'NYSE:XOM', shares: 20 },
  { name: 'IBM', ticker: 'NYSE:IBM', shares: 15 },
  { name: 'BRISTOL MYERS', ticker: 'NYSE:BMY', shares: 50 },
  { name: 'REALTY INCOME', ticker: 'NYSE:O', shares: 25 },
  { name: 'MERCK', ticker: 'NYSE:MRK', shares: 15 },
  { name: 'MEDTRONIC', ticker: 'NYSE:MDT', shares: 10 },
  { name: 'INTEL', ticker: 'NASDAQ:INTC', shares: 50 },
  { name: 'CISCO', ticker: 'NASDAQ:CSCO', shares: 30 },
  { name: 'ALPHABET', ticker: 'NASDAQ:GOOGL', shares: 10 },
  { name: 'MICROSOFT', ticker: 'NASDAQ:MSFT', shares: 5 },
  { name: 'AMAZON', ticker: 'NASDAQ:AMZN', shares: 10 },
  { name: 'JOHNSON & JOHNSON', ticker: 'NYSE:JNJ', shares: 10 },
  { name: 'PROCTER & GAMBLE', ticker: 'NYSE:PG', shares: 25 },
  { name: 'DISNEY', ticker: 'NYSE:DIS', shares: 15 },
  // Fix: changed property name 'NASDAQ' to 'ticker'
  { name: 'KIMBERLY CLARK', ticker: 'NASDAQ:KMB', shares: 10 },
  { name: 'KRAFT HEINZ', ticker: 'NASDAQ:KHC', shares: 50 },
  { name: 'ALTRIA', ticker: 'NYSE:MO', shares: 30 },
  { name: 'VF CORP', ticker: 'NYSE:VFC', shares: 50 },
  { name: 'NIKE', ticker: 'NYSE:NKE', shares: 25 },
  { name: 'T ROWE PRICE', ticker: 'NASDAQ:TROW', shares: 20 },
  { name: 'VERIZON', ticker: 'NYSE:VZ', shares: 50 },
  { name: 'AT&T', ticker: 'NYSE:T', shares: 100 },
  { name: 'JEIP', ticker: 'ETR:JEIP', shares: 50 },
  { name: 'JEQP', ticker: 'ETR:JEQP', shares: 100 },
  { name: 'JGPI', ticker: 'ETR:JGPI', shares: 100 }
];

export const MONTHS = [
  'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'
];
